apiVersion: apps/v1
kind: Deployment
metadata:
  name: stm-pod-cha
  namespace: group1-team6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stm-lbl-cha
  template:
    metadata:
      labels:
        app: stm-lbl-cha
    spec:
      containers:
      - name: stm-contain-cha
        image: k8s-vga-worker1:5000/group1-team6-cha-stm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: team6-stm-cha-sv
  namespace: group1-team6
spec:
  selector:
    app: stm-lbl-cha
  ports:
    - protocol: TCP
      port: 8087 # kube unique inner port
      targetPort: 8099 #listen port, container port, Docker Expose port is equal
      nodePort: 30636
  type: NodePort