server:
  port: 8099
spring:
  kafka:
    bootstrap-servers: 192.168.100.221:30641
  cloud:
    function:
      definition: processMessage
    stream:
      default-binder: kafka-binder
      bindings:
        # Kafka로 메시지 전송하는 바인딩
        kafka-output:
          destination: cha2-topic  # Kafka로 전송할 토픽
        # Kafka에서 메시지 수신하는 바인딩
        processMessage-in-0:
          destination: cha-topic  # Kafka에서 수신할 토픽
          group: local-cha         # Consumer Group
          binder: kafka-binder    # Kafka 바인더 사용
      binders:
        # Kafka 설정
        kafka-binder:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: 192.168.100.221:30641  # Kafka 브로커 주소
                # producer:
                #   key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                #   value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                consumer:
                  group-id: local-cha  # Consumer 그룹 아이디
                  auto-offset-reset: latest  # Kafka에서 소비할 오프셋 위치 (earliest 또는 latest)
                  enable-auto-commit: false  # 자동 커밋 비활성화
                  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
