apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-pod-cha
  namespace: group1-team6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: card-lbl-cha
  template:
    metadata:
      labels:
        app: card-lbl-cha
    spec:
      containers:
      - name: card-contain-cha
        image: k8s-vga-worker1:5000/group1-team6-cha-card:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: team6-card-cha-sv
  namespace: group1-team6
spec:
  selector:
    app: card-lbl-cha
  ports:
    - protocol: TCP
      port: 8088 # kube unique inner port
      targetPort: 8099 #listen port, container port, Docker Expose port is equal
      nodePort: 30631
  type: NodePort