---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team6-eureka-pod-cha
  namespace: group1-team6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-lbl-cha
  template:
    metadata:
      labels:
        app: eureka-lbl-cha
    spec:
      containers:
      - name: eureka-contain-cha
        image: k8s-vga-worker1:5000/group1-team6-eureka-server-cha:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: team6-eureka-cha-sv
  namespace: group1-team6
spec:
  selector:
    app: eureka-lbl-cha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8099
      nodePort: 30635
  type: NodePort
