eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.221:30635/eureka/
      # defaultZone: http://team6-eureka-cha-sv:80/eureka/

spring:
  config:
    import: "optional:configserver:http://192.168.100.221:30633/"
    # import: "optional:configserver:http://team6-cfg-cha-sv:80/"