eureka:
  client:
    serviceUrl:
      defaultZone: http://${SPRING_EUREKA_IMPORT}/eureka/
      # defaultZone: http://team6-eureka-cha-sv:80/eureka/

spring:
  config:
    import: "optional:configserver:http://${SPRING_CONFIG_IMPORT}/"