eureka:
  client:
    serviceUrl:
      defaultZone: http://team6-eureka-cha-sv:80/eureka/
      # defaultZone: http://${SPRING_EUREKA_IMPORT}/eureka/

spring:
  config:
    import: "optional:configserver:http://team6-cfg-cha-sv:80/"
    # import: "optional:configserver:http://${SPRING_CONFIG_IMPORT}/"