apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-dep-cha
  namespace: group1-team6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-pod-cha #pod selectr
  template:
    metadata:
      labels:
        app: account-pod-cha #pod label
    spec:
      containers:
      - name: account-contain-cha
        image: k8s-vga-worker1:5000/group1-team6-cha-acc:latest
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8099
---
apiVersion: v1
kind: Service
metadata:
  name: team6-account-cha-sv
  namespace: group1-team6
spec:
  selector:
    app: account-pod-cha
  ports:
    - protocol: TCP
      port: 80 # kube unique inner port
      targetPort: 8099 #listen port, container port, Docker Expose port is equal
      nodePort: 30632
  type: NodePort