{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile }}
  SPRING_EUREKA_IMPORT: {{ .Values.global.eurekaServerURL }}
  SPRING_CONFIGSERVER_URL: {{ .Values.global.configServerURL }}
{{- end -}}