{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  type: {{ .Values.global.service.type }}
  ports:
    # - name: http
      protocol: TCP
      port: {{ .Values.global.service.port }}
      targetPort: {{ .Values.global.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end -}}